# Generated by Django 2.1 on 2019-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
