# Generated by Django 2.1 on 2019-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todoitem_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
